{% set name = "embree" %}
{% set version = "3.13.0" %}
{% set sha256 = "4d86a69508a7e2eb8710d571096ad024b5174834b84454a8020d3a910af46f4f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/embree/embree/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - use-conda-forge-ABI.patch

build:
  number: 1
  run_exports:
    - {{ pin_subpackage('embree', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]

  host:
    - tbb
    - tbb-devel

test:
  commands:
    - test -f "${PREFIX}/lib/libembree3${SHLIB_EXT}"  # [not win]

about:
  home: https://embree.github.io/
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: High Performance Ray Tracing Kernels

extra:
  recipe-maintainers:
    - joaander
    - scopatz
    - Xarthisius
