{% set name = "embree" %}
{% set version = "4.3.1" %}
{% set sha256 = "824edcbb7a8cd393c5bdb7a16738487b21ecc4e1d004ac9f761e934f97bb02a4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/embree/embree/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - use-conda-forge-ABI.patch

build:
  number: 1
  run_exports:
    - {{ pin_subpackage('embree', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]

  host:
    - tbb
    - tbb-devel

test:
  commands:
    - test -f "${PREFIX}/lib/libembree4${SHLIB_EXT}"  # [not win]

about:
  home: https://embree.github.io/
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: High Performance Ray Tracing Kernels

extra:
  recipe-maintainers:
    - joaander
    - scopatz
    - Xarthisius
