{% set name = "embree" %}
{% set version = "3.2.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz  # [unix]
  url: https://github.com/{{ name }}/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.x86_64.linux.tar.gz  # [linux]
  sha256: ba0bcfa5390e2fdd958af686a0e91b8300eedfbecae126c6e0d2efd0033fc3d4  # [linux]
  url: https://github.com/{{ name }}/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.x86_64.macosx.tar.gz  # [osx]
  sha256: 63f8ae933a26dc70b73ed91aa2421803c544679ff295672485cd427b5e09d81c  # [osx]
  fn: {{ name }}-{{ version }}.zip  # [win]
  url: https://github.com/{{ name }}/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.x64.windows.zip  # [win]
  sha256: 1442062e6b3cd8afa6e4ece13cdcec8c5f643f9e3d3da08618e1917da88e99c6  # [win]

build:
  number: 0
  detect_binary_files_with_prefix: true

requirements:
 build:
  - python  # [win]

test:
  commands:
    - test -f "${PREFIX}/lib/libembree.so"  # [linux]
    - test -f "${PREFIX}/lib/libembree.dylib"  # [osx]

about:
  home: https://embree.github.io/
  license: Apache 2.0
  license_file: doc/LICENSE.txt
  summary: High Performance Ray Tracing Kernels

extra:
  recipe-maintainers:
    - scopatz
    - Xarthisius
