{% set name = "embree" %}
{% set version = "3.11.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz  # [unix]
  url: https://github.com/{{ name }}/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.x86_64.linux.tar.gz  # [linux64]
  sha256: f61ecc7401b8c9444008d53201ec681516f048ee31d43d125dad917fc76c5b71  # [linux64]
  url: https://github.com/{{ name }}/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.x86_64.macosx.zip  # [osx]
  sha256: 81548ebc7689c6451be5409a9395bdf48a6259c0debdc43fe134bc0e5f306448  # [osx]
  fn: {{ name }}-{{ version }}.zip  # [win]
  url: https://github.com/{{ name }}/{{ name }}/archive/{{ version }}.x64.windows.zip  # [win]
  sha256: a47c024a1cdd7d6e7a41dc6e5f0e9de958b0ad5d201788ffaa89af0ce2f9834c  # [win]

build:
  number: 0
  detect_binary_files_with_prefix: true
  skip: true  # [aarch64 or ppc64le]

requirements:
  build:
    - python  # [win]

test:
  commands:
    - test -f "${PREFIX}/lib/libembree.so"  # [linux]
    - test -f "${PREFIX}/lib/libembree.dylib"  # [osx]

about:
  home: https://embree.github.io/
  license: Apache 2.0
  license_file: doc/LICENSE.txt
  summary: High Performance Ray Tracing Kernels

extra:
  recipe-maintainers:
    - scopatz
    - Xarthisius
