{% set name = "embree" %}
{% set version = "3.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz  # [unix]
  url: https://github.com/{{ name }}/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.x86_64.linux.tar.gz  # [linux]
  sha256: 8a07d54bd51dece28fa32d3ba63fbca13fcff8ba261d68ecd156b7c7fd6fbaaf
  url: https://github.com/{{ name }}/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.x86_64.macosx.tar.gz  # [osx]
  sha256: 8a07d54bd51dece28fa32d3ba63fbca13fcff8ba261d68ecd156b7c7fd6fbaaf
  fn: {{ name }}-{{ version }}.zip  # [win]
  url: https://github.com/{{ name }}/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.x64.windows.zip  # [win]
  sha256: 8a07d54bd51dece28fa32d3ba63fbca13fcff8ba261d68ecd156b7c7fd6fbaaf

build:
  number: 0
  detect_binary_files_with_prefix: true

requirements:
 build:
  - python  # [win]

test:
  commands:
    - test -f "${PREFIX}/lib/libembree.so"  # [linux]
    - test -f "${PREFIX}/lib/libembree.dylib"  # [osx]

about:
  home: https://embree.github.io/
  license: Apache 2.0
  license_file: doc/LICENSE.txt
  summary: High Performance Ray Tracing Kernels

extra:
  recipe-maintainers:
    - scopatz
    - Xarthisius
