# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "FqP6nBKnHP/U9CZliHxmZefGQxyYX62EVrFpw++UMAUDYu8YpzUXXc+KHVi+jnbyotzQ5WyX0XT7vqq3kZJqGdYCptW87zNXo8XRKafSiw7IfUWPGOSSMlmzFF2UClc723Hmj3N1ki87xi87BWXtItuQFzj9zP6rmV0bFkTU0cf5vmFKXjA6J9/0oKiATsamJk55b7brcvrDnsLjcmr6rBW8Nklf9JLa5rnvfpHroQEgNlJ5WLIHSL/rTfbulq8De6Mg/XYqQnvxsRc2+AVqpFCP0m3Lr1/MPtiaNxtoUWllJfDylJjHvaefkWvX6teuuM95o8jq+S2bDzuouT07FE6a3zJaaO2Q+Fa46W70022a/Npdj1sIMnY3dIBWerj2lNKRG0gYcw1rM18fchgmaWd8fT5ocXobVI2pEuazETRq2WaFQGpYTim8S6YGCccQ5l8ew+U6Y171vOKs4ZEdjLZJ9xvozhwOAp2LOgFawa6JSYenxWI1ykdTDsX/Y04XldkF5LLnheyPcmf/iCWwJdW5P3rk1SQG7oUzZavXe2N3XZWcXV0hAUnJBiEY6eX72WvGNLTA531PWqry5APUVuKEAPtN+xeWEkZbtegXyNlA8qgCP8tsysRy0mj4OIVqAgaefD80murECHzDjdWNBMm+dUy6yRwT4ImuEf8U7C0="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
